---
- hosts: testgr
  become: true
#  gather_facts: true
#  vars:
#    servers:
#       host1:
#         ip: 192.168.1.20
#         num: 2

  tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
#        var: ansible_facts
         msg:
            - "{{ansible_facts.all_ipv4_addresses[1]}}"
